name: flight_time
description: "Compute the flight time of a jump using the video camera"
publish_to: 'none' 

version: 1.0.2+5

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  camerawesome: ^2.1.0
  video_player: ^2.14.0
  cupertino_icons: ^1.0.9
  sembast: ^3.8.9+1
  path: ^1.9.0
  path_provider: ^2.1.6
  intl: ^0.20.3
  shared_preferences: ^2.5.5
  google_fonts: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  path_provider_linux: ^2.2.1
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/icons/patinage_quebec_logo.png
    - assets/icons/s2m_logo.png
    - assets/fonts/
